import json

with open(
    r"D:\DashboardAQ_v3\archive\ml_model\notebooks\analisis_spasial.ipynb",
    "r",
    encoding="utf-8",
) as f:
    nb = json.load(f)

# Update cell 22 - fix segment counts from 61/65/62 to 60 each
nb["cells"][22]["source"] = [
    "## 7. Interpretasi untuk Bab 4 (Hasil dan Pembahasan)\n",
    "\n",
    "### Ringkasan Data\n",
    "Pengukuran dilakukan pada 10 Juni 2026 di tiga segmen waktu, masing-masing 60 data:\n",
    "- **Ngagel (Pagi, ~07:00-09:06 WIB)** — 60 data, kawasan lalu lintas perkotaan\n",
    "- **Rungkut (Siang, 12:25-13:47 WIB)** — 60 data, kawasan industri manufaktur\n",
    "- **Margomulyo (Sore, 15:47-16:49 WIB)** — 60 data, kawasan industri-logistik & pergudangan\n",
    "\n",
    "Ketiga segmen dipisahkan oleh gap waktu signifikan masing-masing 86 menit, 199 menit, dan 120 menit.\n",
    "\n",
    "### Analisis Per Lokasi\n",
    "\n",
    "**Ngagel (Urban Traffic, Pagi):**\n",
    "- PM2.5 ISPU rata-rata tertinggi (65.16) dengan variasi besar (std 4.55), nilai maksimum mencapai 79.05 ISPU\n",
    "- PM10 ISPU juga tertinggi (rata-rata 32.97, maks 50.92)\n",
    "- CO ISPU paling rendah (rata-rata 15.41) — emisi kendaraan pagi hari belum terakumulasi\n",
    "- Suhu rata-rata 34.15°C dengan kelembapan rata-rata 57.96% (tertinggi)\n",
    "- Variabilitas kelembapan sangat tinggi (std 6.82), menunjukkan transisi dari pagi ke siang\n",
    "- **Interpretasi:** Polusi partikulat (PM2.5, PM10) dominan akibat emisi kendaraan bermotor di jam sibuk pagi hari. Suhu masih relatif rendah sehingga lapisan inversi atmosferik pagi hari dapat memerangkap polutan di dekat permukaan.\n",
    "\n",
    "**Rungkut (Industri Manufaktur, Siang):**\n",
    "- PM2.5 ISPU menengah (rata-rata 53.99, std 2.41) lebih rendah dari Ngagel\n",
    "- PM10 ISPU menengah (rata-rata 21.26)\n",
    "- CO ISPU tertinggi (rata-rata 20.53, maks 23.46) — indikasi emisi dari aktivitas industri manufaktur\n",
    "- Suhu meningkat (rata-rata 35.09°C), kelembapan menurun (rata-rata 51.39%)\n",
    "- **Interpretasi:** Polusi CO yang tinggi mencerminkan emisi pembakaran dari proses industri manufaktur. Suhu yang lebih tinggi dan kelembapan lebih rendah disebabkan oleh waktu pengukuran siang hari. Partikulat lebih rendah dibanding Ngagel karena lapisan batas atmosferik lebih tebal (pencampuran vertikal lebih baik).\n",
    "\n",
    "**Margomulyo (Industri Logistik, Sore):**\n",
    "- PM2.5 ISPU terendah (rata-rata 41.06) dengan variasi tinggi (std 5.33)\n",
    "- PM10 ISPU terendah (rata-rata 13.72)\n",
    "- CO ISPU menengah (rata-rata 20.31), mendekati Rungkut\n",
    "- Suhu tertinggi (rata-rata 35.92°C), kelembapan terendah (rata-rata 48.11%)\n",
    "- **Interpretasi:** Polutan partikulat lebih rendah karena kelembapan rendah dan pencampuran vertikal sore hari yang lebih baik. CO masih cukup tinggi karena aktivitas kendaraan logistik (truk/gudang) pada sore hari. Suhu tertinggi akibat akumulasi panas harian.\n",
    "\n",
    "### Perbandingan Antar Lokasi\n",
    "\n",
    "| Parameter | Tertinggi | Lokasi | Selisih dengan Terendah |\n",
    "|-----------|-----------|--------|------------------------|\n",
    "| PM2.5 ISPU | 65.16 | Ngagel | +24.10 (vs Margomulyo) |\n",
    "| PM10 ISPU | 32.97 | Ngagel | +19.25 (vs Margomulyo) |\n",
    "| CO ISPU | 20.53 | Rungkut | +5.12 (vs Ngagel) |\n",
    "| Suhu | 35.92°C | Margomulyo | +1.76°C (vs Ngagel) |\n",
    "| Kelembapan | 57.96% | Ngagel | +9.86% (vs Margomulyo) |\n",
    "\n",
    "Pola spasial menunjukkan **dikotomi polutan-partikulat vs gas**:\n",
    "- PM2.5 dan PM10 dominan di kawasan **lalu lintas perkotaan (Ngagel)**\n",
    "- CO dominan di kawasan **industri manufaktur (Rungkut)**\n",
    "- Margomulyo sebagai kawasan logistik menunjukkan profil polutan yang lebih ringan secara umum\n",
    "\n",
    "### Analisis Pengaruh Suhu dan Kelembapan\n",
    "\n",
    "Berdasarkan scatter plot dan matriks korelasi:\n",
    "- **PM2.5 vs Suhu** (r = -0.5662): Korelasi negatif sedang. Semakin tinggi suhu, PM2.5 cenderung menurun. Hal ini disebabkan oleh pencampuran vertikal yang lebih baik saat suhu tinggi (siang-sore), yang mengencerkan konsentrasi partikulat di permukaan.\n",
    "- **PM2.5 vs Kelembapan** (r = +0.6431): Korelasi positif sedang. Kelembapan tinggi (pagi hari) berkaitan dengan PM2.5 tinggi karena: (1) inversi atmosferik pagi memerangkap polutan, (2) kelembapan tinggi memfasilitasi pertumbuhan aerosol higroskopis.\n",
    "- **CO vs Suhu** (r = +0.2591): Korelasi positif lemah. CO sedikit meningkat dengan suhu, mencerminkan peningkatan emisi dari aktivitas industri dan logistik pada siang-sore hari.\n",
    "- **CO vs Kelembapan** (r = -0.3606): Korelasi negatif lemah. CO cenderung lebih rendah saat kelembapan tinggi (pagi), karena sumber emisi CO (kendaraan pagi) lebih rendah dibanding sumber industri siang hari.\n",
    "\n",
    "- **PM2.5 vs PM10** (r = +0.9336): Korelasi positif sangat kuat, mengonfirmasi kedua partikulat berasal dari sumber yang sama (debu jalan, emisi kendaraan).\n",
    "- **Suhu vs Kelembapan** (r = -0.9106): Korelasi negatif sangat kuat, hubungan fisis yang diharapkan.\n",
    "\n",
    "**Apakah temperatur lebih tinggi selalu menghasilkan kualitas udara lebih buruk?**\n",
    "Tidak. Data menunjukkan hubungan yang lebih kompleks:\n",
    "1. Suhu tertinggi di Margomulyo (35.92°C) justru berkorelasi dengan PM2.5 terendah (41.06 ISPU)\n",
    "2. Suhu terendah di Ngagel (34.15°C) justru berkorelasi dengan PM2.5 tertinggi (65.16 ISPU)\n",
    "3. Hal ini terjadi karena pengaruh waktu pengukuran (pencampuran vertikal atmosferik) dan karakteristik sumber emisi lebih dominan dibanding efek suhu semata.\n",
    "4. Suhu tinggi justru dapat memperbaiki kualitas udara partikulat melalui peningkatan tinggi lapisan campuran (mixing layer height), sementara suhu rendah pagi hari dengan inversi termal justru memerangkap polutan.\n",
    "\n",
    "### Kaitan dengan Karakteristik Wilayah\n",
    "\n",
    "**Ngagel — Lalu Lintas Perkotaan:**\n",
    "Ciri khas kawasan ini adalah tingginya partikulat (PM2.5, PM10) akibat emisi kendaraan bermotor pada jam sibuk pagi hari. Variabilitas kelembapan yang tinggi mencerminkan transisi kondisi atmosferik dari pagi ke siang. Hasil ini konsisten dengan karakteristik Ngagel sebagai koridor transportasi utama Surabaya.\n",
    "\n",
    "**Rungkut — Industri Manufaktur:**\n",
    "Dominasi CO ISPU dan suhu menengah mencerminkan emisi pembakaran dari proses industri manufaktur yang berlangsung pada siang hari. Variabilitas rendah pada hampir semua parameter menunjukkan kondisi yang relatif stabil selama operasi industri.\n",
    "\n",
    "**Margomulyo — Industri Logistik dan Pergudangan:**\n",
    "Suhu tertinggi dan kelembapan terendah merupakan ciri pengukuran sore hari. Polutan partikulat yang lebih rendah menunjukkan bahwa kawasan ini tidak memiliki sumber emisi partikulat dominan. CO menengah mengindikasikan kontribusi dari kendaraan logistik.\n",
    "\n",
    "### Kesimpulan\n",
    "1. **PM2.5 dan PM10 tertinggi di Ngagel** (kawasan lalu lintas perkotaan, pagi hari), menunjukkan bahwa emisi kendaraan bermotor pada jam sibuk pagi merupakan kontributor utama partikulat di udara. Lapisan inversi pagi hari memperparah akumulasi polutan di permukaan.\n",
    "2. **CO tertinggi di Rungkut** (kawasan industri manufaktur, siang hari), mengindikasikan emisi pembakaran dari aktivitas industri sebagai sumber dominan karbon monoksida.\n",
    "3. **Temperatur bukan faktor penentu tunggal kualitas udara.** Hubungan suhu dengan polutan partikulat bersifat negatif (r = -0.57) karena efek pencampuran vertikal atmosferik lebih dominan. Polutan gas (CO) menunjukkan hubungan positif lemah dengan suhu (r = +0.26) karena aktivitas sumber emisi (industri, logistik) yang meningkat pada suhu lebih tinggi.\n",
    "4. **Kelembapan memiliki hubungan positif dengan PM2.5** (r = +0.64), terutama karena kelembapan tinggi pada pagi hari berkaitan dengan kondisi inversi atmosferik yang memerangkap polutan.\n",
    "5. **Ketiga kawasan menunjukkan profil polusi yang berbeda** sesuai karakteristik masing-masing: lalu lintas perkotaan (partikulat dominan), industri manufaktur (CO dominan), dan industri logistik (polutan lebih ringan).\n",
]

with open(
    r"D:\DashboardAQ_v3\archive\ml_model\notebooks\analisis_spasial.ipynb",
    "w",
    encoding="utf-8",
) as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Cell 22 updated")
